#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ZhuoHuaAPP.Resource", IsApplication=true)]

namespace ZhuoHuaAPP
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040030
			public const int aliceblue = 2130968624;
			
			// aapt resource value: 0x7f040026
			public const int antiquewhite = 2130968614;
			
			// aapt resource value: 0x7f040086
			public const int aqua = 2130968710;
			
			// aapt resource value: 0x7f040067
			public const int aquamarine = 2130968679;
			
			// aapt resource value: 0x7f04002e
			public const int azure = 2130968622;
			
			// aapt resource value: 0x7f04002b
			public const int beige = 2130968619;
			
			// aapt resource value: 0x7f040011
			public const int bisque = 2130968593;
			
			// aapt resource value: 0x7f040095
			public const int black = 2130968725;
			
			// aapt resource value: 0x7f04000f
			public const int blanchedalmond = 2130968591;
			
			// aapt resource value: 0x7f040091
			public const int blue = 2130968721;
			
			// aapt resource value: 0x7f04005f
			public const int blueviolet = 2130968671;
			
			// aapt resource value: 0x7f040054
			public const int brown = 2130968660;
			
			// aapt resource value: 0x7f040038
			public const int burlywood = 2130968632;
			
			// aapt resource value: 0x7f040075
			public const int cadetblue = 2130968693;
			
			// aapt resource value: 0x7f040068
			public const int chartreuse = 2130968680;
			
			// aapt resource value: 0x7f040043
			public const int chocolate = 2130968643;
			
			// aapt resource value: 0x7f04001b
			public const int coral = 2130968603;
			
			// aapt resource value: 0x7f040074
			public const int cornflowerblue = 2130968692;
			
			// aapt resource value: 0x7f04000b
			public const int cornsilk = 2130968587;
			
			// aapt resource value: 0x7f04003b
			public const int crimson = 2130968635;
			
			// aapt resource value: 0x7f040087
			public const int cyan = 2130968711;
			
			// aapt resource value: 0x7f040093
			public const int darkblue = 2130968723;
			
			// aapt resource value: 0x7f04008d
			public const int darkcyan = 2130968717;
			
			// aapt resource value: 0x7f04004b
			public const int darkgoldenrod = 2130968651;
			
			// aapt resource value: 0x7f040052
			public const int darkgray = 2130968658;
			
			// aapt resource value: 0x7f040090
			public const int darkgreen = 2130968720;
			
			// aapt resource value: 0x7f040053
			public const int darkgrey = 2130968659;
			
			// aapt resource value: 0x7f040048
			public const int darkkhaki = 2130968648;
			
			// aapt resource value: 0x7f04005d
			public const int darkmagenta = 2130968669;
			
			// aapt resource value: 0x7f040076
			public const int darkolivegreen = 2130968694;
			
			// aapt resource value: 0x7f04001a
			public const int darkorange = 2130968602;
			
			// aapt resource value: 0x7f040056
			public const int darkorchid = 2130968662;
			
			// aapt resource value: 0x7f04005e
			public const int darkred = 2130968670;
			
			// aapt resource value: 0x7f040035
			public const int darksalmon = 2130968629;
			
			// aapt resource value: 0x7f04005b
			public const int darkseagreen = 2130968667;
			
			// aapt resource value: 0x7f040079
			public const int darkslateblue = 2130968697;
			
			// aapt resource value: 0x7f04007f
			public const int darkslategray = 2130968703;
			
			// aapt resource value: 0x7f040080
			public const int darkslategrey = 2130968704;
			
			// aapt resource value: 0x7f04008b
			public const int darkturquoise = 2130968715;
			
			// aapt resource value: 0x7f040058
			public const int darkviolet = 2130968664;
			
			// aapt resource value: 0x7f04001f
			public const int deeppink = 2130968607;
			
			// aapt resource value: 0x7f04008c
			public const int deepskyblue = 2130968716;
			
			// aapt resource value: 0x7f040071
			public const int dimgray = 2130968689;
			
			// aapt resource value: 0x7f040072
			public const int dimgrey = 2130968690;
			
			// aapt resource value: 0x7f040084
			public const int dodgerblue = 2130968708;
			
			// aapt resource value: 0x7f04004c
			public const int firebrick = 2130968652;
			
			// aapt resource value: 0x7f040009
			public const int floralwhite = 2130968585;
			
			// aapt resource value: 0x7f040082
			public const int forestgreen = 2130968706;
			
			// aapt resource value: 0x7f040020
			public const int fuchsia = 2130968608;
			
			// aapt resource value: 0x7f04003a
			public const int gainsboro = 2130968634;
			
			// aapt resource value: 0x7f040028
			public const int ghostwhite = 2130968616;
			
			// aapt resource value: 0x7f040015
			public const int gold = 2130968597;
			
			// aapt resource value: 0x7f04003d
			public const int goldenrod = 2130968637;
			
			// aapt resource value: 0x7f040062
			public const int gray = 2130968674;
			
			// aapt resource value: 0x7f04008f
			public const int green = 2130968719;
			
			// aapt resource value: 0x7f040002
			public const int green1 = 2130968578;
			
			// aapt resource value: 0x7f040050
			public const int greenyellow = 2130968656;
			
			// aapt resource value: 0x7f040063
			public const int grey = 2130968675;
			
			// aapt resource value: 0x7f04002f
			public const int honeydew = 2130968623;
			
			// aapt resource value: 0x7f04001c
			public const int hotpink = 2130968604;
			
			// aapt resource value: 0x7f040045
			public const int indianred = 2130968645;
			
			// aapt resource value: 0x7f040077
			public const int indigo = 2130968695;
			
			// aapt resource value: 0x7f040005
			public const int ivory = 2130968581;
			
			// aapt resource value: 0x7f040031
			public const int khaki = 2130968625;
			
			// aapt resource value: 0x7f040036
			public const int lavender = 2130968630;
			
			// aapt resource value: 0x7f04000d
			public const int lavenderblush = 2130968589;
			
			// aapt resource value: 0x7f040069
			public const int lawngreen = 2130968681;
			
			// aapt resource value: 0x7f04000a
			public const int lemonchiffon = 2130968586;
			
			// aapt resource value: 0x7f040051
			public const int lightblue = 2130968657;
			
			// aapt resource value: 0x7f040032
			public const int lightcoral = 2130968626;
			
			// aapt resource value: 0x7f040037
			public const int lightcyan = 2130968631;
			
			// aapt resource value: 0x7f040024
			public const int lightgoldenrodyellow = 2130968612;
			
			// aapt resource value: 0x7f040040
			public const int lightgray = 2130968640;
			
			// aapt resource value: 0x7f04005a
			public const int lightgreen = 2130968666;
			
			// aapt resource value: 0x7f040041
			public const int lightgrey = 2130968641;
			
			// aapt resource value: 0x7f040000
			public const int lightorange = 2130968576;
			
			// aapt resource value: 0x7f040017
			public const int lightpink = 2130968599;
			
			// aapt resource value: 0x7f040019
			public const int lightsalmon = 2130968601;
			
			// aapt resource value: 0x7f040083
			public const int lightseagreen = 2130968707;
			
			// aapt resource value: 0x7f040060
			public const int lightskyblue = 2130968672;
			
			// aapt resource value: 0x7f04006b
			public const int lightslategray = 2130968683;
			
			// aapt resource value: 0x7f04006c
			public const int lightslategrey = 2130968684;
			
			// aapt resource value: 0x7f04004e
			public const int lightsteelblue = 2130968654;
			
			// aapt resource value: 0x7f040006
			public const int lightyellow = 2130968582;
			
			// aapt resource value: 0x7f040089
			public const int lime = 2130968713;
			
			// aapt resource value: 0x7f04007e
			public const int limegreen = 2130968702;
			
			// aapt resource value: 0x7f040025
			public const int linen = 2130968613;
			
			// aapt resource value: 0x7f040003
			public const int lucency = 2130968579;
			
			// aapt resource value: 0x7f040021
			public const int magenta = 2130968609;
			
			// aapt resource value: 0x7f040066
			public const int maroon = 2130968678;
			
			// aapt resource value: 0x7f040073
			public const int mediumaquamarine = 2130968691;
			
			// aapt resource value: 0x7f040092
			public const int mediumblue = 2130968722;
			
			// aapt resource value: 0x7f04004a
			public const int mediumorchid = 2130968650;
			
			// aapt resource value: 0x7f040059
			public const int mediumpurple = 2130968665;
			
			// aapt resource value: 0x7f04007d
			public const int mediumseagreen = 2130968701;
			
			// aapt resource value: 0x7f04006a
			public const int mediumslateblue = 2130968682;
			
			// aapt resource value: 0x7f04008a
			public const int mediumspringgreen = 2130968714;
			
			// aapt resource value: 0x7f040078
			public const int mediumturquoise = 2130968696;
			
			// aapt resource value: 0x7f040046
			public const int mediumvioletred = 2130968646;
			
			// aapt resource value: 0x7f040085
			public const int midnightblue = 2130968709;
			
			// aapt resource value: 0x7f040029
			public const int mintcream = 2130968617;
			
			// aapt resource value: 0x7f040010
			public const int mistyrose = 2130968592;
			
			// aapt resource value: 0x7f040012
			public const int moccasin = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int navajowhite = 2130968595;
			
			// aapt resource value: 0x7f040094
			public const int navy = 2130968724;
			
			// aapt resource value: 0x7f040023
			public const int oldlace = 2130968611;
			
			// aapt resource value: 0x7f040064
			public const int olive = 2130968676;
			
			// aapt resource value: 0x7f04006f
			public const int olivedrab = 2130968687;
			
			// aapt resource value: 0x7f040018
			public const int orange = 2130968600;
			
			// aapt resource value: 0x7f04001e
			public const int orangered = 2130968606;
			
			// aapt resource value: 0x7f04003e
			public const int orchid = 2130968638;
			
			// aapt resource value: 0x7f040033
			public const int palegoldenrod = 2130968627;
			
			// aapt resource value: 0x7f040057
			public const int palegreen = 2130968663;
			
			// aapt resource value: 0x7f04004f
			public const int paleturquoise = 2130968655;
			
			// aapt resource value: 0x7f04003c
			public const int palevioletred = 2130968636;
			
			// aapt resource value: 0x7f04000e
			public const int papayawhip = 2130968590;
			
			// aapt resource value: 0x7f040014
			public const int peachpuff = 2130968596;
			
			// aapt resource value: 0x7f040044
			public const int peru = 2130968644;
			
			// aapt resource value: 0x7f040016
			public const int pink = 2130968598;
			
			// aapt resource value: 0x7f040039
			public const int plum = 2130968633;
			
			// aapt resource value: 0x7f04004d
			public const int powderblue = 2130968653;
			
			// aapt resource value: 0x7f040065
			public const int purple = 2130968677;
			
			// aapt resource value: 0x7f040022
			public const int red = 2130968610;
			
			// aapt resource value: 0x7f040049
			public const int rosybrown = 2130968649;
			
			// aapt resource value: 0x7f04007b
			public const int royalblue = 2130968699;
			
			// aapt resource value: 0x7f04005c
			public const int saddlebrown = 2130968668;
			
			// aapt resource value: 0x7f040027
			public const int salmon = 2130968615;
			
			// aapt resource value: 0x7f04002d
			public const int sandybrown = 2130968621;
			
			// aapt resource value: 0x7f040081
			public const int seagreen = 2130968705;
			
			// aapt resource value: 0x7f04000c
			public const int seashell = 2130968588;
			
			// aapt resource value: 0x7f040055
			public const int sienna = 2130968661;
			
			// aapt resource value: 0x7f040047
			public const int silver = 2130968647;
			
			// aapt resource value: 0x7f040061
			public const int skyblue = 2130968673;
			
			// aapt resource value: 0x7f040070
			public const int slateblue = 2130968688;
			
			// aapt resource value: 0x7f04006d
			public const int slategray = 2130968685;
			
			// aapt resource value: 0x7f04006e
			public const int slategrey = 2130968686;
			
			// aapt resource value: 0x7f040008
			public const int snow = 2130968584;
			
			// aapt resource value: 0x7f040088
			public const int springgreen = 2130968712;
			
			// aapt resource value: 0x7f04007a
			public const int steelblue = 2130968698;
			
			// aapt resource value: 0x7f040042
			public const int tan = 2130968642;
			
			// aapt resource value: 0x7f04008e
			public const int teal = 2130968718;
			
			// aapt resource value: 0x7f04003f
			public const int thistle = 2130968639;
			
			// aapt resource value: 0x7f040001
			public const int titlebar_btnpressed = 2130968577;
			
			// aapt resource value: 0x7f04001d
			public const int tomato = 2130968605;
			
			// aapt resource value: 0x7f040096
			public const int transparent = 2130968726;
			
			// aapt resource value: 0x7f04007c
			public const int turquoise = 2130968700;
			
			// aapt resource value: 0x7f040034
			public const int violet = 2130968628;
			
			// aapt resource value: 0x7f04002c
			public const int wheat = 2130968620;
			
			// aapt resource value: 0x7f040004
			public const int white = 2130968580;
			
			// aapt resource value: 0x7f04002a
			public const int whitesmoke = 2130968618;
			
			// aapt resource value: 0x7f040007
			public const int yellow = 2130968583;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050004
			public const int body_padding = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int body_size = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int hander_padding = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int hander_size = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int title_padding = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int title_size = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int borderBlue = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int borderBlue2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int borderGray = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_check_off = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_check_off_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btn_check_off_selected = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_check_on = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_check_on_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_check_on_selected = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int CunQian1 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int CunQian2 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Exhibition1 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Exhibition2 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Exhibition3 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Exhibition4 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int finance = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int GoldStock1 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int GoldStock2 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int homepage1 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int homepage2 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_navigation_next_item_1 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_pulltorefresh_arrow = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Icon = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Img_SettingServer = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int login_edit_borderBlue = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int MapStore1 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int MapStore2 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int PicButton = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int product = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int q1 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int q2 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int q3 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int q4 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int qq_btn_check = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int Query = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int sales = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int shape_bottom_corner_no_top_line = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int shape_no_corner_without_bottom = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int shape_top_corner_no_bottom_line = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int splash1 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int splash2 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int splash_background = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int Store1 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int Store2 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int Tab1 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int Tab2 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int Tab3 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int Tab4 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int Tab5 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int tileSelectorGreen = 2130837553;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080037
			public const int BT_background1 = 2131230775;
			
			// aapt resource value: 0x7f08004a
			public const int Button_goMain = 2131230794;
			
			// aapt resource value: 0x7f080031
			public const int Iv_Finance = 2131230769;
			
			// aapt resource value: 0x7f08002b
			public const int Iv_Product = 2131230763;
			
			// aapt resource value: 0x7f080034
			public const int Iv_Query = 2131230772;
			
			// aapt resource value: 0x7f08002e
			public const int Iv_Sales = 2131230766;
			
			// aapt resource value: 0x7f080046
			public const int RelativeLayout_bg = 2131230790;
			
			// aapt resource value: 0x7f080049
			public const int RelativeLayout_bottom = 2131230793;
			
			// aapt resource value: 0x7f08004b
			public const int RelativeLayout_middleleft = 2131230795;
			
			// aapt resource value: 0x7f080047
			public const int RelativeLayout_top = 2131230791;
			
			// aapt resource value: 0x7f080038
			public const int Relot1_2 = 2131230776;
			
			// aapt resource value: 0x7f08003a
			public const int TextView01_2 = 2131230778;
			
			// aapt resource value: 0x7f08003c
			public const int TextView02_2 = 2131230780;
			
			// aapt resource value: 0x7f080035
			public const int dividers = 2131230773;
			
			// aapt resource value: 0x7f08002c
			public const int dividers1 = 2131230764;
			
			// aapt resource value: 0x7f08002f
			public const int dividers2 = 2131230767;
			
			// aapt resource value: 0x7f080032
			public const int dividers3 = 2131230770;
			
			// aapt resource value: 0x7f080001
			public const int idCompany = 2131230721;
			
			// aapt resource value: 0x7f080040
			public const int imageButton1 = 2131230784;
			
			// aapt resource value: 0x7f08002a
			public const int linearLayout1 = 2131230762;
			
			// aapt resource value: 0x7f080000
			public const int linearLayout_Company = 2131230720;
			
			// aapt resource value: 0x7f080030
			public const int linearLayout_Finance = 2131230768;
			
			// aapt resource value: 0x7f080028
			public const int linearLayout_Function = 2131230760;
			
			// aapt resource value: 0x7f080022
			public const int linearLayout_GetSale = 2131230754;
			
			// aapt resource value: 0x7f080011
			public const int linearLayout_InOut = 2131230737;
			
			// aapt resource value: 0x7f080029
			public const int linearLayout_Product = 2131230761;
			
			// aapt resource value: 0x7f080033
			public const int linearLayout_Query = 2131230771;
			
			// aapt resource value: 0x7f08002d
			public const int linearLayout_Sale = 2131230765;
			
			// aapt resource value: 0x7f080010
			public const int linearLayout_Today = 2131230736;
			
			// aapt resource value: 0x7f08003f
			public const int login_Auto = 2131230783;
			
			// aapt resource value: 0x7f08003d
			public const int login_btn_login_2 = 2131230781;
			
			// aapt resource value: 0x7f08003e
			public const int login_cb_savepwd_2 = 2131230782;
			
			// aapt resource value: 0x7f080039
			public const int login_edit_account_2 = 2131230777;
			
			// aapt resource value: 0x7f08003b
			public const int login_edit_pwd_2 = 2131230779;
			
			// aapt resource value: 0x7f080041
			public const int pull_to_refresh_header = 2131230785;
			
			// aapt resource value: 0x7f080043
			public const int pull_to_refresh_image = 2131230787;
			
			// aapt resource value: 0x7f080042
			public const int pull_to_refresh_progress = 2131230786;
			
			// aapt resource value: 0x7f080044
			public const int pull_to_refresh_text = 2131230788;
			
			// aapt resource value: 0x7f080045
			public const int pull_to_refresh_updated_at = 2131230789;
			
			// aapt resource value: 0x7f080027
			public const int scrollView1 = 2131230759;
			
			// aapt resource value: 0x7f080013
			public const int tableLayout1 = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int tableRow1 = 2131230740;
			
			// aapt resource value: 0x7f080016
			public const int tableRow2 = 2131230742;
			
			// aapt resource value: 0x7f080018
			public const int tableRow3 = 2131230744;
			
			// aapt resource value: 0x7f08001a
			public const int tableRow4 = 2131230746;
			
			// aapt resource value: 0x7f08001c
			public const int tableRow5 = 2131230748;
			
			// aapt resource value: 0x7f08001e
			public const int tableRow6 = 2131230750;
			
			// aapt resource value: 0x7f080020
			public const int tableRow7 = 2131230752;
			
			// aapt resource value: 0x7f080023
			public const int tdNoCheckOrderCount = 2131230755;
			
			// aapt resource value: 0x7f080015
			public const int tdOrderCount = 2131230741;
			
			// aapt resource value: 0x7f080017
			public const int tdOrderPrice = 2131230743;
			
			// aapt resource value: 0x7f080021
			public const int tdPayable = 2131230753;
			
			// aapt resource value: 0x7f080019
			public const int tdProductCount = 2131230745;
			
			// aapt resource value: 0x7f080024
			public const int tdPurchaseQuotationCount = 2131230756;
			
			// aapt resource value: 0x7f08001f
			public const int tdReceivable = 2131230751;
			
			// aapt resource value: 0x7f080025
			public const int tdSaleQuotationCount = 2131230757;
			
			// aapt resource value: 0x7f080026
			public const int tdSalebookCount = 2131230758;
			
			// aapt resource value: 0x7f08001b
			public const int tdSendOutCount = 2131230747;
			
			// aapt resource value: 0x7f08001d
			public const int tdStoreCount = 2131230749;
			
			// aapt resource value: 0x7f080012
			public const int textView1 = 2131230738;
			
			// aapt resource value: 0x7f08000a
			public const int textView10 = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int textView11 = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int textView12 = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int textView13 = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int textView14 = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int textView15 = 2131230735;
			
			// aapt resource value: 0x7f080002
			public const int textView2 = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int textView3 = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int textView4 = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int textView5 = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int textView6 = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int textView7 = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int textView8 = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int textView9 = 2131230729;
			
			// aapt resource value: 0x7f08004d
			public const int view_middle_area = 2131230797;
			
			// aapt resource value: 0x7f08004c
			public const int view_middleleft = 2131230796;
			
			// aapt resource value: 0x7f080048
			public const int view_top = 2131230792;
			
			// aapt resource value: 0x7f08004e
			public const int webView1 = 2131230798;
			
			// aapt resource value: 0x7f080036
			public const int widget33_2 = 2131230774;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int aboutus = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int homepage = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int homepage2 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int login = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int pull_to_refresh_header = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int test = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int webviewlayout = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int pull_to_refresh_pull_label = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int pull_to_refresh_refreshing_label = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int pull_to_refresh_release_label = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int pull_to_refresh_tap_label = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int tv_Company = 2131099654;
			
			// aapt resource value: 0x7f06000e
			public const int tv_NoCheckOrderCount = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int tv_PurchaseQuotationCount = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int tv_SaleQuotationCount = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int tv_SalebookCount = 2131099665;
			
			// aapt resource value: 0x7f060007
			public const int tv_tdOrderCount = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int tv_tdOrderPrice = 2131099656;
			
			// aapt resource value: 0x7f06000d
			public const int tv_tdPayable = 2131099661;
			
			// aapt resource value: 0x7f060009
			public const int tv_tdProductCount = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int tv_tdReceivable = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int tv_tdSendOutCount = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int tv_tdStoreCount = 2131099659;
			
			// aapt resource value: 0x7f060016
			public const int tv_test_Data = 2131099670;
			
			// aapt resource value: 0x7f060014
			public const int tv_title_Finance = 2131099668;
			
			// aapt resource value: 0x7f060012
			public const int tv_title_Product = 2131099666;
			
			// aapt resource value: 0x7f060015
			public const int tv_title_Query = 2131099669;
			
			// aapt resource value: 0x7f060013
			public const int tv_title_Sale = 2131099667;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
