//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.34014 版自动生成。
// 
#pragma warning disable 1591

namespace ZhuoHuaAPP.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ISimpDbServer", Namespace="http://tempuri.org/")]
    public partial class SimpDbServer : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DataRequest_By_StringOperationCompleted;
        
        private System.Threading.SendOrPostCallback DataRequest_By_DataTableOperationCompleted;
        
        private System.Threading.SendOrPostCallback DataRequest_By_DataSetOperationCompleted;
        
        private System.Threading.SendOrPostCallback DataRequest_By_SimpDEsOperationCompleted;
        
        private System.Threading.SendOrPostCallback DataRequest_By_SimpDEs_GZipOperationCompleted;
        
        private System.Threading.SendOrPostCallback DataRequest_By_SimpDEs_All_GZipOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SimpDbServer() {
            this.Url = "http://localhost:13124/SimpDbServer";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DataRequest_By_StringCompletedEventHandler DataRequest_By_StringCompleted;
        
        /// <remarks/>
        public event DataRequest_By_DataTableCompletedEventHandler DataRequest_By_DataTableCompleted;
        
        /// <remarks/>
        public event DataRequest_By_DataSetCompletedEventHandler DataRequest_By_DataSetCompleted;
        
        /// <remarks/>
        public event DataRequest_By_SimpDEsCompletedEventHandler DataRequest_By_SimpDEsCompleted;
        
        /// <remarks/>
        public event DataRequest_By_SimpDEs_GZipCompletedEventHandler DataRequest_By_SimpDEs_GZipCompleted;
        
        /// <remarks/>
        public event DataRequest_By_SimpDEs_All_GZipCompletedEventHandler DataRequest_By_SimpDEs_All_GZipCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISimpDbServer/DataRequest_By_String", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DataRequest_By_String([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string _methodRequests) {
            object[] results = this.Invoke("DataRequest_By_String", new object[] {
                        _methodRequests});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DataRequest_By_StringAsync(string _methodRequests) {
            this.DataRequest_By_StringAsync(_methodRequests, null);
        }
        
        /// <remarks/>
        public void DataRequest_By_StringAsync(string _methodRequests, object userState) {
            if ((this.DataRequest_By_StringOperationCompleted == null)) {
                this.DataRequest_By_StringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDataRequest_By_StringOperationCompleted);
            }
            this.InvokeAsync("DataRequest_By_String", new object[] {
                        _methodRequests}, this.DataRequest_By_StringOperationCompleted, userState);
        }
        
        private void OnDataRequest_By_StringOperationCompleted(object arg) {
            if ((this.DataRequest_By_StringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DataRequest_By_StringCompleted(this, new DataRequest_By_StringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISimpDbServer/DataRequest_By_DataTable", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable DataRequest_By_DataTable([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string _methodRequests) {
            object[] results = this.Invoke("DataRequest_By_DataTable", new object[] {
                        _methodRequests});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void DataRequest_By_DataTableAsync(string _methodRequests) {
            this.DataRequest_By_DataTableAsync(_methodRequests, null);
        }
        
        /// <remarks/>
        public void DataRequest_By_DataTableAsync(string _methodRequests, object userState) {
            if ((this.DataRequest_By_DataTableOperationCompleted == null)) {
                this.DataRequest_By_DataTableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDataRequest_By_DataTableOperationCompleted);
            }
            this.InvokeAsync("DataRequest_By_DataTable", new object[] {
                        _methodRequests}, this.DataRequest_By_DataTableOperationCompleted, userState);
        }
        
        private void OnDataRequest_By_DataTableOperationCompleted(object arg) {
            if ((this.DataRequest_By_DataTableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DataRequest_By_DataTableCompleted(this, new DataRequest_By_DataTableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISimpDbServer/DataRequest_By_DataSet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet DataRequest_By_DataSet([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string _methodRequests) {
            object[] results = this.Invoke("DataRequest_By_DataSet", new object[] {
                        _methodRequests});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void DataRequest_By_DataSetAsync(string _methodRequests) {
            this.DataRequest_By_DataSetAsync(_methodRequests, null);
        }
        
        /// <remarks/>
        public void DataRequest_By_DataSetAsync(string _methodRequests, object userState) {
            if ((this.DataRequest_By_DataSetOperationCompleted == null)) {
                this.DataRequest_By_DataSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDataRequest_By_DataSetOperationCompleted);
            }
            this.InvokeAsync("DataRequest_By_DataSet", new object[] {
                        _methodRequests}, this.DataRequest_By_DataSetOperationCompleted, userState);
        }
        
        private void OnDataRequest_By_DataSetOperationCompleted(object arg) {
            if ((this.DataRequest_By_DataSetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DataRequest_By_DataSetCompleted(this, new DataRequest_By_DataSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISimpDbServer/DataRequest_By_SimpDEs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DataRequest_By_SimpDEs([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string _methodRequests) {
            object[] results = this.Invoke("DataRequest_By_SimpDEs", new object[] {
                        _methodRequests});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DataRequest_By_SimpDEsAsync(string _methodRequests) {
            this.DataRequest_By_SimpDEsAsync(_methodRequests, null);
        }
        
        /// <remarks/>
        public void DataRequest_By_SimpDEsAsync(string _methodRequests, object userState) {
            if ((this.DataRequest_By_SimpDEsOperationCompleted == null)) {
                this.DataRequest_By_SimpDEsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDataRequest_By_SimpDEsOperationCompleted);
            }
            this.InvokeAsync("DataRequest_By_SimpDEs", new object[] {
                        _methodRequests}, this.DataRequest_By_SimpDEsOperationCompleted, userState);
        }
        
        private void OnDataRequest_By_SimpDEsOperationCompleted(object arg) {
            if ((this.DataRequest_By_SimpDEsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DataRequest_By_SimpDEsCompleted(this, new DataRequest_By_SimpDEsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISimpDbServer/DataRequest_By_SimpDEs_GZip", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] DataRequest_By_SimpDEs_GZip([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string _methodRequests) {
            object[] results = this.Invoke("DataRequest_By_SimpDEs_GZip", new object[] {
                        _methodRequests});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void DataRequest_By_SimpDEs_GZipAsync(string _methodRequests) {
            this.DataRequest_By_SimpDEs_GZipAsync(_methodRequests, null);
        }
        
        /// <remarks/>
        public void DataRequest_By_SimpDEs_GZipAsync(string _methodRequests, object userState) {
            if ((this.DataRequest_By_SimpDEs_GZipOperationCompleted == null)) {
                this.DataRequest_By_SimpDEs_GZipOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDataRequest_By_SimpDEs_GZipOperationCompleted);
            }
            this.InvokeAsync("DataRequest_By_SimpDEs_GZip", new object[] {
                        _methodRequests}, this.DataRequest_By_SimpDEs_GZipOperationCompleted, userState);
        }
        
        private void OnDataRequest_By_SimpDEs_GZipOperationCompleted(object arg) {
            if ((this.DataRequest_By_SimpDEs_GZipCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DataRequest_By_SimpDEs_GZipCompleted(this, new DataRequest_By_SimpDEs_GZipCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISimpDbServer/DataRequest_By_SimpDEs_All_GZip", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] DataRequest_By_SimpDEs_All_GZip([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)] byte[] _methodBts) {
            object[] results = this.Invoke("DataRequest_By_SimpDEs_All_GZip", new object[] {
                        _methodBts});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void DataRequest_By_SimpDEs_All_GZipAsync(byte[] _methodBts) {
            this.DataRequest_By_SimpDEs_All_GZipAsync(_methodBts, null);
        }
        
        /// <remarks/>
        public void DataRequest_By_SimpDEs_All_GZipAsync(byte[] _methodBts, object userState) {
            if ((this.DataRequest_By_SimpDEs_All_GZipOperationCompleted == null)) {
                this.DataRequest_By_SimpDEs_All_GZipOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDataRequest_By_SimpDEs_All_GZipOperationCompleted);
            }
            this.InvokeAsync("DataRequest_By_SimpDEs_All_GZip", new object[] {
                        _methodBts}, this.DataRequest_By_SimpDEs_All_GZipOperationCompleted, userState);
        }
        
        private void OnDataRequest_By_SimpDEs_All_GZipOperationCompleted(object arg) {
            if ((this.DataRequest_By_SimpDEs_All_GZipCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DataRequest_By_SimpDEs_All_GZipCompleted(this, new DataRequest_By_SimpDEs_All_GZipCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void DataRequest_By_StringCompletedEventHandler(object sender, DataRequest_By_StringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DataRequest_By_StringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DataRequest_By_StringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void DataRequest_By_DataTableCompletedEventHandler(object sender, DataRequest_By_DataTableCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DataRequest_By_DataTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DataRequest_By_DataTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void DataRequest_By_DataSetCompletedEventHandler(object sender, DataRequest_By_DataSetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DataRequest_By_DataSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DataRequest_By_DataSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void DataRequest_By_SimpDEsCompletedEventHandler(object sender, DataRequest_By_SimpDEsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DataRequest_By_SimpDEsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DataRequest_By_SimpDEsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void DataRequest_By_SimpDEs_GZipCompletedEventHandler(object sender, DataRequest_By_SimpDEs_GZipCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DataRequest_By_SimpDEs_GZipCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DataRequest_By_SimpDEs_GZipCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void DataRequest_By_SimpDEs_All_GZipCompletedEventHandler(object sender, DataRequest_By_SimpDEs_All_GZipCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DataRequest_By_SimpDEs_All_GZipCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DataRequest_By_SimpDEs_All_GZipCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591